name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame
        pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
        pip install pylint
        pip install pytest
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
